version: '3.8'

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
